apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: generator-bq-latency
  labels:
    service_name: generator
    feature_name: bq
    slo_name: latency
    team: team1
    env: test
spec:
  goal: 0.99
  description: >
    99% of BigQuery API HTTP response latencies < 400ms
  backend: cloud_monitoring/team1
  method: distribution_cut
  exporters:
  - cloud_monitoring/team1
  - cloud_monitoring/sre
  - bigquery/sre
  - pubsub/sre
  service_level_indicator:
    filter_valid: >
      metric.type="serviceruntime.googleapis.com/api/request_latencies"
      resource.type="consumed_api"
      resource.label."project_id"="${TEAM1_PROJECT_ID}"
      resource.label."service"="bigquery.googleapis.com"
    good_below_threshold: true
    threshold_bucket: 17
