apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: generator-pubsub-ack
  labels:
    service_name: generator
    feature_name: pubsub
    slo_name: ack
    team: team2
    env: test
spec:
  description: 99% of outstanding PubSub messages are acknowledged
  backend: cloud_monitoring/team2
  method: good_bad_ratio
  exporters:
  - bigquery
  - cloud_monitoring
  - cloud_monitoring/team2
  - pubsub
  service_level_indicator:
    filter_good: >
      project="${TEAM2_PROJECT_ID}"
      metric.type="pubsub.googleapis.com/subscription/ack_message_count"
      resource.type="pubsub_subscription"
    filter_bad: >
      project="${TEAM2_PROJECT_ID}"
      metric.type="pubsub.googleapis.com/subscription/num_outstanding_messages"
      resource.type="pubsub_subscription"
  goal: 0.99
