---

backends:
  cloud_monitoring/team1:
    project_id: ${TEAM1_PROJECT_ID}
  cloud_monitoring/team2:
    project_id: ${TEAM2_PROJECT_ID}

exporters:
  bigquery:
    project_id: ${SRE_PROJECT_ID}
    dataset_id: ${BIGQUERY_DATASET_ID}
    table_id: reports
  cloud_monitoring:
    project_id: ${SRE_PROJECT_ID}
  cloud_monitoring/team2:
    project_id: ${TEAM1_PROJECT_ID}
  pubsub:
    project_id: ${SRE_PROJECT_ID}
    topic_name: ${SRE_PUBSUB_TOPIC_NAME}

error_budget_policies:
  default:
    steps:
    - name: a.Last 1 hour
      burn_rate_threshold: 9
      alert: true
      message_alert: Page to defend the SLO
      message_ok: Last hour on track
      window: 3600
    - name: b.Last 12 hours
      burn_rate_threshold: 3
      alert: true
      message_alert: Page to defend the SLO
      message_ok: Last 12 hours on track
      window: 43200
    - name: c.Last 7 days
      burn_rate_threshold: 1.5
      alert: false
      message_alert: Dev team dedicates 25% of engineers to the reliability backlog
      message_ok: Last week on track
      window: 604800
    - name: d.Last 28 days
      burn_rate_threshold: 1
      alert: false
      message_alert: Freeze release, unless related to reliability or security
      message_ok: Unfreeze release, per the agreed roll-out policy
      window: 2419200
