apiVersion: sre.google.com/v2
kind: ServiceLevelObjective
metadata:
  name: slo-generator-errors
  labels:
    service_name: slo-generator
    feature_name: cloudrun
    slo_name: errors
    team: sre
    env: test
spec:
  goal: 0.99
  description: 99% of requests to Cloud Run service have a good HTTP status code
  backend: cloud_monitoring
  method: good_bad_ratio
  exporters:
  - cloud_monitoring/sre
  - bigquery/sre
  - pubsub/sre
  service_level_indicator:
    filter_good: >
      project="${SRE_PROJECT_ID}"
      metric.type="run.googleapis.com/request_count"
      metric.label."response_code_class"="2xx"
    filter_valid: >
      project="${SRE_PROJECT_ID}"
      metric.type="run.googleapis.com/request_count"
